Use [DAI_Survey_EDA]
go

with cte_asp as (
	select [aspect]
		,[asp_count] = count(distinct [Item_ID])
	from [dbo].[aspect_Item_Bank]
	group by [aspect]
)
,cte_grp as (
	select
		[aspect]
		,[aspect_group] = case 
							when [aspect] in (
								'activities'
								,'activity'
								,'breakout rooms'
								,'class activities'
								,'class discussion'
								,'class discussions'
								,'debate'
								,'debates'
								,'discussion'
								,'Discussion Board'
								,'discussions'
								,'exercise'
								,'exercises'
								,'game'
								,'games'
								,'group'
								,'group activities'
								,'group discussions'
								,'groups'
								,'interview'
								,'- lab'
								,'lab'
								,'lab sessions'
								,'lab work'
								,'labs'
								,'learning activities'
								,'meetings'
								,'prac'
								,'pracs'
								,'practical activities'
								,'coding exercises'
								,'interactive sessions'
								,'laboratory'
								,'learning practices'
								,'masterclasses'
								,'mindfulness'
								,'mindfulness sessions'
								,'mindfulness training'
								,'Moblab'
								,'Moblab experiments'
								,'Open Lab'
								,'practical sessions'
								,'pre - class'
								,'studio experience'
								,'subject activities'
								,'Team Roles'
								,'tour'
											)
								then 'activity'
							when [aspect] in (
								'approach'
								,'atmosphere'
								,'communication'
								,'interactive'
								,'method'
								,'methods'
								,'teaching methods'
								,'teaching style'
								,'methodology'
											)
								then 'approach'
							when [aspect] in (
								'assessment'
								,'assessment briefs'
								,'Assessment criteria'
								,'assessment structure'
								,'assessment task'
								,'assessment tasks'
								,'assessments'
								,'attendance'
								,'Challenge'
								,'criteria'
								,'description'
								,'exam'
								,'exams'
								,'group assessment'
								,'Preparation'
								,'question'
								,'questions'
								,'quiz'
								,'quiz questions'
								,'quizes'
								,'quizzes'
								,'reflection'
								,'report'
								,'reports'
								,'requirements'
								,'results'
								,'task'
								,'tasks'
								,'test'
								,'Tests'
								,'weighting'
								,'about assessment'
								,'final exam'
								,'group - based assessment'
								,'lab quizzes'
								,'Mastery'
								,'midterm'
								,'online assessments'
								,'project presentation'
											)
								then 'assessment'
							when [aspect] in (
								'assignment'
								,'assignments'
								,'code'
								,'coding'
								,'deadlines'
								,'direction'
								,'grade'
								,'grades'
								,'grading'
								,'group assignment'
								,'group assignments'
								,'group project'
								,'group work'
								,'groupwork'
								,'homework'
								,'homework questions'
								,'marking'
								,'marking criteria'
								,'marks'
								,'presentation'
								,'presentations'
								,'programming'
								,'project'
								,'projects'
								,'submission'
								,'submissions'
								,'word'
								,'word count'
								,'wording'
								,'words'
								,'work'
								,'work load'
								,'working'
								,'workload'
								,'writing'
								,'project stream'
								,'Python coding'
											)
								then 'assignment'
							when [aspect] in (
								'class'
								,'class time'
								,'classes'
								,'classroom'
								,'day'
								,'face'
								,'format'
								,'forum'
								,'hours'
								,'interesting'
								,'length'
								,'lesson'
								,'Lessons'
								,'online'
								,'platform'
								,'quality'
								,'seminar'
								,'seminars'
								,'session'
								,'sessions'
								,'study'
								,'time'
								,'time management'
								,'times'
								,'timing'
								,'video lectures'
								,'Zoom'
								,'Zoom sessions'
								,'face - to'
								,'face - to - face'
								,'face time'
								,'learning module'
								,'lecture videos'
								,'online modules'
								,'video lesson'
								,'Zoom webinars'
											)
								then 'class'
							when [aspect] in (
								'brief'
								,'briefs'
								,'case'
								,'case studies'
								,'case study'
								,'cases'
								,'chapters'
								,'components'
								,'concept'
								,'concepts'
								,'content'
								,'contents'
								,'context'
								,'culture'
								,'delivered'
								,'delivery'
								,'explained'
								,'explanation'
								,'explanations'
								,'focus'
								,'formulas'
								,'Fundamentals'
								,'history'
								,'ideas'
								,'INFO'
								,'information'
								,'introduction'
								,'issues'
								,'layout'
								,'lecture notes'
								,'points'
								,'problem'
								,'problems'
								,'PROCESS'
								,'stuff'
								,'subject content'
								,'topic'
								,'Topics'
								,'Advanced Topics'
								,'clinical case scenarios'
								,'clinical scenarios'
								,'content material'
								,'exposure'
								,'organ system'
								,'video techniques'
								,'what content'
								,'discipline'
											)
								then 'content'
							when [aspect] in (
								'course'
								,'Course structure'
								,'courses'
								,'coursework'
								,'curriculum'
								,'elective'
								,'electives'
								,'semester'
								,'Service'
								,'syllabus'
								,'system'
								,'catering'
								,'course design'
								,'expectations'
								,'microcredential'
											)
								then 'course'
							when [aspect] in (
								'environment'
								,'learning environment'
								,'lecture room'
								,'room'
								,'rooms'
								,'setting'
								,'Site'
								,'space'
								,'table'
								,'tables'
								,'technology'
								,'SocialHub'
								,'VPN'
								,'VPN service'
								,'accessing'
											)
								then 'environment'
							when [aspect] in (
								'answer'
								,'answers'
								,'demonstration'
								,'demonstrations'
											)
								then 'explanation'
							when [aspect] in (
								'comments'
								,'feedback'
								,'feedback sessions'
								,'feedbacks'
								,'review'
								,'solutions'
								,'suggestions'
								,'waiting'
								,'journal'
								,'Q'
								,'Q & A'
								,'Q & A sessions'
								,'video log'
								,'Webassign'
											)
								then 'feedback'
							when [aspect] in (
								'guidance'
								,'guide'
								,'Guidelines'
								,'help'
								,'instruction'
								,'instructions'
								,'revision'
								,'support'
								,'tutes'
								,'tutorial'
								,'tutorials'
								,'tuts'
								,'workshop'
								,'workshops'
								,'Getting'
								,'guides'
								,'live tutorial sessions'
								,'of coaching'
								,'revision class'
								,'Revision Sessions'
											)
								then 'guidance'
							when [aspect] in (
								'all'
								,'everything'
								,'pre - work'
								,'the'
								,'1070'
								,'think'
											)
								then 'ignore'
							when [aspect] in (
								'education'
								,'experience'
								,'learn'
								,'learned'
								,'Learning'
								,'learnings'
								,'objectives'
								,'opportunities'
								,'skill'
								,'skills'
								,'techniques'
								,'theories'
								,'theory'
								,'understanding'
								,'learning about'
								,'learning experiences'
								,'Objective'
								,'strategies'
								,'your learning'
											)
								then 'learning'
							when [aspect] in (
								'lecture'
								,'Lecture content'
								,'lecture time'
								,'lectures'
								,'lecturing'
								,'live lectures'
								,'pace'
								,'presented'
								,'speed'
								,'subjects lectures'
											)
								then 'lecture'
							when [aspect] in (
								'application'
								,'applications'
								,'internship'
								,'internships'
								,'life'
								,'placement'
								,'placements'
								,'portfolio'
								,'practical'
								,'practical work'
								,'Practicals'
								,'practice'
								,'practice questions'
								,'practices'
								,'profession'
								,'career workshops'
								,'Event'
								,'selection criteria'
								,'the skills I'
											)
								then 'practicability'
							when [aspect] in (
								'area'
								,'areas'
								,'background'
											)
								then 'scope'
							when [aspect] in (
								'class participation'
								,'Engagement'
								,'interaction'
								,'learnt'
								,'motivation'
								,'participation'
								,'people'
								,'performance'
								,'person'
								,'stress'
								,'students'
								,'team'
								,'teams'
								,'self'
											)
								then 'student'
							when [aspect] in (
								'animation'
								,'Architecture'
								,'construction'
								,'cost'
								,'design'
								,'designs'
								,'field'
								,'Industry'
								,'knowledge'
								,'law'
								,'Learning objectives'
								,'learning opportunities'
								,'management'
								,'marketing'
								,'module'
								,'modules'
								,'organisation'
								,'outline'
								,'program'
								,'range'
								,'schedule'
								,'Scope'
								,'sections'
								,'standards'
								,'structure'
								,'subject'
								,'subject matter'
								,'subject outline'
								,'subject structure'
								,'subjects'
								,'themes'
								,'time frame'
								,'timetable'
								,'unit'
								,'units'
								,'value'
								,'week'
								,'Fashion'
								,'Fashion Techniques'
								,'flexibility'
								,'health'
								,'many lectures and'
								,'Migration'
								,'of flexibility offered'
								,'studio stream'
								,'the quality'
											)
								then 'subject'
							when [aspect] in (
								'Alex'
								,'Andrew'
								,'Anna'
								,'Anne'
								,'attitude'
								,'Ben'
								,'care'
								,'Chris'
								,'coordinator'
								,'coordinators'
								,'David'
								,'demonstrators'
								,'educator'
								,'facilitator'
								,'George'
								,'Greg'
								,'guest lectures'
								,'guest speakers'
								,'guy'
								,'Helen'
								,'helpful'
								,'Ian'
								,'instructor'
								,'instructors'
								,'James'
								,'job'
								,'John'
								,'Kate'
								,'language'
								,'leader'
								,'lecturer'
								,'Lecturers'
								,'Maria'
								,'Mark'
								,'Martin'
								,'Matt'
								,'Michael'
								,'Nina'
								,'Paul'
								,'Peter'
								,'presenters'
								,'Prof'
								,'professor'
								,'professors'
								,'Rob'
								,'Sara'
								,'Sarah'
								,'Scott'
								,'simon'
								,'speaker'
								,'speakers'
								,'staff'
								,'staff member'
								,'style'
								,'subject coordinator'
								,'supervisor'
								,'supervisors'
								,'talk'
								,'taught'
								,'teach'
								,'teacher'
								,'teachers'
								,'teaches'
								,'teaching'
								,'teaching staff'
								,'teachings'
								,'Tim'
								,'tom'
								,'training'
								,'tutor'
								,'tutors'
								,'voice'
								,'assistant demonstrator'
								,'AWA'
								,'demonstrator'
								,'expertise'
								,'Mentor'
								,'mentors'
								,'presenter'
								,'principal'
								,'Project Executive'
								,'teaching assistants'
								,'technical staff'
											)
								then 'teacher'
							when [aspect] in (
								'articles'
								,'audio'
								,'blackboard'
								,'board'
								,'canvas'
								,'diagrams'
								,'equipment'
								,'essay'
								,'essays'
								,'example'
								,'examples'
								,'excel'
								,'experiments'
								,'facilities'
								,'films'
								,'google'
								,'kahoot'
								,'Kahoot Quizzes'
								,'kahoots'
								,'lecture recordings'
								,'lecture slides'
								,'links'
								,'material'
								,'materials'
								,'media'
								,'movies'
								,'Music'
								,'notes'
								,'paper'
								,'papers'
								,'photoshop'
								,'pictures'
								,'pitch'
								,'podcasts'
								,'PowerPoint'
								,'Powerpoint slides'
								,'Powerpoints'
								,'PPT'
								,'programs'
								,'reading'
								,'readings'
								,'recordings'
								,'research'
								,'resources'
								,'scenarios'
								,'screen'
								,'simulation'
								,'slide'
								,'slides'
								,'software'
								,'softwares'
								,'Sound'
								,'studio'
								,'subject material'
								,'text'
								,'textbook'
								,'texts'
								,'use'
								,'video'
								,'videos'
								,'workbook'
								,'worksheets'
								,'E - learning materials'
								,'material content'
								,'news'
								,'NewsDay'
								,'page'
								,'simulation activities'
								,'simulations'
								,'templates'
								,'video links'
											)
								then 'teaching material'
							when [aspect] in ('tools'
								,'CloudStor'
								,'Forms'
								,'ingredient pack'
								,'ingredients'
								,'interactive audience response systems'
								,'interactive learning tools'
								,'learning dimensions'
								,'Microsoft Teams'
								,'Mindmaps'
								,'Toolkit'
								,'useful tool'
								,'WRAP Toolkit'
											)
								then 'tool'
							when [aspect] in ('UTS'
								,'administration'
								,'look and feel'
								,'school'
											)
								then 'UTS'
							else 'Unknown'
						end
	from [cte_asp]
)
--select
--	g.[aspect_group]
--	,b.[aspect]
--	,b.[Item_ID]
--	--,[grp_count] = count(distinct [aspect])
update b set [aspect_group] = g.[aspect_group]
from [cte_grp] g
join [dbo].[aspect_Item_Bank] b on b.[aspect] = g.[aspect]
where 1=1
--and [aspect_group] = 'Unknown'
--group by [aspect_group]
--order by [grp_count] desc
--order by [aspect]
go

select
	[aspect_group],
	[grp_count] = count(distinct [Item_ID])
from [dbo].[aspect_Item_Bank]
group by [aspect_group]
order by count(distinct [Item_ID]) desc
go

select
	[aspect_group],
	[grp_count] = count(distinct [Item_ID])
from [dbo].[aspect_Item_Bank]
group by [aspect_group]
order by count(distinct [Item_ID]) desc
go
